### ISSUE TITLE
Minor issue - Color defines in .h file commented out prevents compile of example program

### ISSUE THREAD

**Issue by mharrow** [KrisKasprzak/ILI9341_t3_controls#3]
Enjoy using your Graphics Library. While converting Example programs to use XPT2046 noticed that program wouldn't compile because the color defines have been commented out in the ILI9341_t3_controls.h file. Previous version of your library that I downloaded didn't have this issue.

Again thanks for making this library available.

**Comment by KrisKasprzak** [comment]
Examples should all be fixed--color defs now include in the examples
