### ISSUE TITLE
Several examples use utouch.h, but this is an obsolete library no longer supported

### ISSUE THREAD

**Issue by bdlabitt** [KrisKasprzak/ILI9341_t3_controls#6]
I was looking at using this library.  However, I found in your examples there is an import of utouch.h.

This library does not seem to be actively maintained - it is not in the Arduino library manager.  Do you know where I can find it?  Or can some of these examples be written using #include <XPT2046_Touchscreen.h> ?  Thanks.

**Comment by KrisKasprzak** [comment]
I’ll fix the examples to use the XPT 2046 libraryThanks.Kris KasprzakOn Mar 25, 2023, at 12:10 PM, bdlabitt ***@***.***> wrote:﻿
I was looking at using this library.  However, I found in your examples there is an import of utouch.h.
This library does not seem to be actively maintained - it is not in the Arduino library manager.  Do you know where I can find it?  Or can some of these examples be written using #include <XPT2046_Touchscreen.h> ?  Thanks.

**Comment by KrisKasprzak** [comment]
Changed all examples to use the XPT2046_Touchscreen.h
